export const levels = {
  1: {
    ground: [
      { x: 0, y: window.innerHeight - 40, width: 2000, height: 64 },
      { x: 3900, y: window.innerHeight - 40, width: 450, height: 64 },
      { x: 3600, y: window.innerHeight - 40, width: 150, height: 64 },
    ],
    ground2: [
      { x: 0, y: window.innerHeight - -15, width: 2000, height: 128 },
      { x: 3900, y: window.innerHeight - -15, width: 450, height: 128 },
      { x: 3600, y: window.innerHeight - -15, width: 150, height: 128 },
    ],
    platforms: [
      { x: 2080, y: window.innerHeight - 90, width: 200, height: 50 },
      { x: 2400, y: window.innerHeight - 150, width: 300, height: 50 },
      { x: 2850, y: window.innerHeight - 200, width: 150, height: 50 },
      { x: 3150, y: window.innerHeight - 150, width: 300, height: 50 },
      { x: 3200, y: window.innerHeight - 300, width: 100, height: 50 },
      { x: 3400, y: window.innerHeight - 350, width: 250, height: 50 },
      { x: 3550, y: window.innerHeight - 500, width: 200, height: 50 },
      { x: 3450, y: window.innerHeight - 100, width: 150, height: 50 },
      { x: 3900, y: window.innerHeight - 550, width: 150, height: 50 },
      { x: 4200, y: window.innerHeight - 200, width: 300, height: 50 },
      { x: 4650, y: window.innerHeight - 250, width: 200, height: 50 },
      { x: 4810, y: window.innerHeight - 600, width: 100, height: 50 },
      { x: 5000, y: window.innerHeight - 650, width: 350, height: 50 },
      { x: 5350, y: window.innerHeight - 700, width: 150, height: 50 },
      { x: 5450, y: window.innerHeight - 950, width: 150, height: 50 },
      { x: 5600, y: window.innerHeight - 90, width: 500, height: 50 },
    ],
    ladders: [
      { x: 3300, y: window.innerHeight - 300, width: 64, height: 150 },
      { x: 3500, y: window.innerHeight - 500, width: 64, height: 150 },
      { x: 4750, y: window.innerHeight - 600, width: 64, height: 350 },
      { x: 5400, y: window.innerHeight - 950, width: 64, height: 250 },
    ],
    signs: [
      {
        x: 1900,
        y: window.innerHeight - 90,
        width: 64,
        height: 50,
        text: "Bem-vindo ao mundo do caos, bravo guerreiro! Espero que esteja pronto para enfrentar o mundo de aventura que foi preparado para você. Temos diversos desafios que lhe serão propostos! Este é um mundo de aventuras, aonde você foi escolhido para ser nosso guerreiro, espero que não se incomode. Irei lhe esclareçer algumas coisas para arremessar suas espadas, basta pressionar X, para que possa pular, pressione Espaço. Não tenho mais nada para lhe passar, agora você está por conta própria, tenha cuidado em sua jornada, pois ela será realmente desafiadora.",
      },
      {
        x: 2500,
        y: window.innerHeight - 200,
        width: 64,
        height: 50,
        text: "Cuidado com os inimigos! Eles podem te fazer coceguinhas, hahaha, não. Mas falando sério agora, espero que não desista de sua jornada, ela promete ser recompensadora e desafiadora, ou nem tanto quato pensa, mas garanto que irá se diverir",
      },
      {
        x: 2900,
        y: window.innerHeight - 250,
        width: 64,
        height: 50,
        text: "Tesouros aguardam aqueles que são corajosos! Ou a morte, ela também.",
      },
      {
        x: 3230,
        y: window.innerHeight - 200,
        width: 64,
        height: 50,
        text: "Clique Enter para abrir interagir com basicamente tudo, assim como as placas.",
      },
      {
        x: 5470,
        y: window.innerHeight - 1000,
        width: 64,
        height: 50,
        text: "Tomara que você tenha vida o suficiente, pois é uma dura queda.",
      },
    ],
    enemies: [
      {
        x: 2100,
        y: window.innerHeight - 145,
        velX: 1,
        velY: 0,
        width: 64,
        height: 64,
      },
      {
        x: 2620,
        y: window.innerHeight - 205,
        velX: -1,
        velY: 0,
        width: 50,
        height: 50,
      },
      {
        x: 3210,
        y: window.innerHeight - 355,
        velX: 1,
        velY: 0,
        width: 50,
        height: 50,
      },
      {
        x: 4650,
        y: window.innerHeight - 300,
        velX: -1,
        velY: 0,
        width: 50,
        height: 50,
      },
    ],
    blocks1: [
      {
        x: 5800,
        y: window.innerHeight - 150,
        width: 64,
        height: 64,
      },
    ],
    torches: [
      { x: 3500, y: window.innerHeight - 250, width: 64, height: 64 },
      { x: 3650, y: window.innerHeight - 425, width: 64, height: 64 },
    ],
    heartCollectables: [
      { x: 2200, y: window.innerHeight - 120, id: 1 },
      { x: 5550, y: window.innerHeight - 980, id: 2 },
    ],
    playerStart: { x: 64, y: window.innerHeight - 40 - 64 },
    },
  2: {
    ground: [{ x: 0, y: window.innerHeight - 40, width: 600, height: 64 }],
    ground2: [{ x: 0, y: window.innerHeight - -15, width: 600, height: 128 }],
    platforms: [],
    ladders: [],
    signs: [],
    enemies: [],
    blocks1: [],
    torches: [],
    heartCollectables: [],
    guardian: {
      x: 150,
      y: window.innerHeight - 215,
      width: 200,
      height: 200,
      text: "Saudações, nobre guerreiro. Vejo que é novo por estas bandas, prazer, sou o guardião do castelo, irei lhe apresentar ao rei, para que possa estar coletando sua missão, vejo que veio da floresta, então deve ser um forte guerreiro. Bem, eu também já fui um aventureiro então sei o quão divertido é caçar criaturas, haha. Enfim, pode seguir pela estrada, espero que pegue uma missão desafiadora!"
    },
    background: 'castle.avif',
    playerStart: { x: 64, y: window.innerHeight - 40 - 64 },
   },
}; 